// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihDNMv0j_QjRYiU3bRrS5Ap21dA1sYqU',
    appId: '1:756855490028:web:0dff14ace160f793d5acc9',
    messagingSenderId: '756855490028',
    projectId: 'tactix-academy',
    authDomain: 'tactix-academy.firebaseapp.com',
    storageBucket: 'tactix-academy.firebasestorage.app',
    measurementId: 'G-NEFTB8VCDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYx2NT-80EGZpFG3b_nXI1j9Q4gHrXXo',
    appId: '1:756855490028:android:6a56af88de4b8933d5acc9',
    messagingSenderId: '756855490028',
    projectId: 'tactix-academy',
    storageBucket: 'tactix-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6-6NW2L0W4I_cvgIHZT6pbpJV65mSFa8',
    appId: '1:756855490028:ios:438a8d26e5a811bed5acc9',
    messagingSenderId: '756855490028',
    projectId: 'tactix-academy',
    storageBucket: 'tactix-academy.firebasestorage.app',
    androidClientId: '756855490028-0qbqh1pk1vro1a0ukbhb5c3kgfurd59q.apps.googleusercontent.com',
    iosClientId: '756855490028-9pcl48i4todnvthmbgu6ablfbbuh5993.apps.googleusercontent.com',
    iosBundleId: 'com.example.tactixAcademyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6-6NW2L0W4I_cvgIHZT6pbpJV65mSFa8',
    appId: '1:756855490028:ios:438a8d26e5a811bed5acc9',
    messagingSenderId: '756855490028',
    projectId: 'tactix-academy',
    storageBucket: 'tactix-academy.firebasestorage.app',
    androidClientId: '756855490028-0qbqh1pk1vro1a0ukbhb5c3kgfurd59q.apps.googleusercontent.com',
    iosClientId: '756855490028-9pcl48i4todnvthmbgu6ablfbbuh5993.apps.googleusercontent.com',
    iosBundleId: 'com.example.tactixAcademyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihDNMv0j_QjRYiU3bRrS5Ap21dA1sYqU',
    appId: '1:756855490028:web:fa61ba1d0a23a201d5acc9',
    messagingSenderId: '756855490028',
    projectId: 'tactix-academy',
    authDomain: 'tactix-academy.firebaseapp.com',
    storageBucket: 'tactix-academy.firebasestorage.app',
    measurementId: 'G-19T7FWNHZ0',
  );
}
